In [2]:
import numpy as np

# Matrix operations

In [6]:
# Create a matrix
A = np.array([
    [1,  2,  3],
    [4,  5,  6],
    [-2, -4, 8]
])
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [-2, -4,  8]])

In [7]:
# Create a range of numbers
B = np.arange(1,10)
B

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# Create a matrix by reshaping a list
C = B.reshape(3,3)
C

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
D = np.arange(0,16,2)
E = D.reshape(4,2)
E

In [21]:
# Transposing way 1
E.T

array([[ 0,  4,  8, 12],
       [ 2,  6, 10, 14]])

In [22]:
# Transposing way 2
E.transpose()

array([[ 0,  4,  8, 12],
       [ 2,  6, 10, 14]])

In [25]:
# Kfoneger produxt (item by item)
A * C

array([[  1,   4,   9],
       [ 16,  25,  36],
       [-14, -32,  72]])

## Matrix Multiplication

In [31]:
# Matrix Multiplication using .dot()
F = A.dot(C)
F

array([[30, 36, 42],
       [66, 81, 96],
       [38, 40, 42]])

In [59]:
# Using np.matmul
np.matmul(A,C)

array([[30, 36, 42],
       [66, 81, 96],
       [38, 40, 42]])

## Matrix diagonal

In [41]:
# Diagonal de la matrix
F.diagonal()

array([30, 81, 42])

In [29]:
# Matrix trace of the main diagonal (sum of diagonal)
F.trace()

153

In [42]:
# Alternative way to calculate the trce
F.diagonal().sum()

153

In [36]:
# Invertir el orden de la matriz, para calcular la traza de la otra diagonal
F_reversed=F[::-1]

In [39]:
F_reversed.trace()

161

## Linear Algebra Methods - Eingenvalues

In [52]:
# Eingenvalues
np.linalg.eigvals(A)


array([-0.50973293+0.j        ,  7.25486647+5.45554775j,
        7.25486647-5.45554775j])

In [54]:
# both eingenvalues and eigenvectors
eigenvalues, eingenvectors = np.linalg.eig(A)
eingenvectors

array([[-0.83719254+0.j        ,  0.29796807+0.03994244j,
         0.29796807-0.03994244j],
       [ 0.54373581+0.j        ,  0.71681106+0.j        ,
         0.71681106-0.j        ],
       [ 0.05882184+0.j        ,  0.07074016+0.62513787j,
         0.07074016-0.62513787j]])

## Linear Algebra Methods - Inverse

In [56]:
# Inverse
A_inverse = np.linalg.inv(A)
A_inverse

array([[-1.52380952,  0.66666667,  0.07142857],
       [ 1.04761905, -0.33333333, -0.14285714],
       [ 0.14285714,  0.        ,  0.07142857]])

In [58]:
# Corroboratio  of inversion
A_inverse.dot(A)

array([[ 1.00000000e+00,  4.99600361e-16,  7.77156117e-16],
       [-1.11022302e-16,  1.00000000e+00, -4.44089210e-16],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

## Higher dimention arrays

In [73]:
my_3D_array = np.arange(1,91)
my_3D_array.shape = (3,3,10)
my_3D_array


array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]],

       [[31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]],

       [[61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
        [71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
        [81, 82, 83, 84, 85, 86, 87, 88, 89, 90]]])

In [74]:
my_3D_array[0]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [75]:
my_3D_array[0,1]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [76]:
my_3D_array[0,1,0]

11